[package]
name = "pawkit-lua"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pawkit-logger.workspace = true
pawkit-net.workspace = true
pawkit-net-signaling.workspace = true

mlua.workspace = true
