[package]
name = "pawkit-bitarray"
version = "0.1.2"
edition = "2024"
license = "MPL-2.0"
homepage = "https://teamvulpine.com"
repository = "https://github.com/TeamVulpine/PawKit/tree/main/bitarray"
description = "A dynamically sized bit array"

[dependencies]
